version: '2'

services:
  db:
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret123'
      POSTGRES_DB: 'scheduler'
    ports:
      - '9432:5432'
