server:
  port: ${PORT:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true # https://hibernate.atlassian.net/browse/HHH-12368
  datasource:
    url: ${DB_CONNECTION_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:9432}}/${DB_NAME:scheduler}?currentSchema=${DB_SCHEMA_NAME:public}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret123}

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: [ "classpath:/db/postgresql" ]
    schemas: [ "${DB_SCHEMA_NAME:public}" ]


  quartz:
    scheduler-name: demo
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: demo
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: qrtz_
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5

